# Generated by Django 3.1.12 on 2024-11-20 18:34

from django.db import migrations, models
import djongo.models.fields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('headline', models.CharField(max_length=200)),
                ('skills', models.JSONField()),
                
            ],
        ),
    ]
