# Generated by Django 3.1.12 on 2024-11-23 12:57

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=djongo.models.fields.JSONField(),
        ),
    ]
